# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Forms.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(825, 602)
        Dialog.setMinimumSize(QtCore.QSize(591, 0))
        Dialog.setStyleSheet("background-color:rgb(54, 54, 54)")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(310, 60, 131, 51))
        self.label.setStyleSheet("color:rgb(230, 255, 244);\n"
"font-size : 28px;")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(130, 185, 191, 31))
        self.label_2.setStyleSheet("font-size:15px;\n"
"color:rgb(255, 80, 223);\n"
"")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(100, 250, 47, 13))
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(400, 190, 291, 31))
        self.lineEdit.setStyleSheet("font-size:14px;\n"
"color:white;")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(400, 280, 291, 31))
        self.lineEdit_2.setStyleSheet("font-size:14px;\n"
"color:white;")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(130, 275, 191, 41))
        self.label_4.setStyleSheet("font-size:15px;\n"
"color:rgb(255, 80, 223);")
        self.label_4.setObjectName("label_4")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(250, 420, 261, 31))
        self.pushButton.setStyleSheet("font-size:16px;\n"
"color:rgb(255, 0, 255);\n"
"background-color:rgb(255, 208, 235);")
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        self.label.setText(_translate("Dialog", "Login"))
        self.label_2.setText(_translate("Dialog", "UserName"))
        self.label_4.setText(_translate("Dialog", "Password"))
        self.pushButton.setText(_translate("Dialog", "Login"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
